name: Build renv environments

on:
  push:
    paths:
      - '**/renv.lock'
  workflow_dispatch: 

jobs:
  build-renv:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4.1'

    - name: Set up renv
      uses: r-lib/actions/setup-renv@v2
   
    - name: Find changed renv.lock files
      id: find-changes
      run: |
        echo "files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'renv.lock')" >> $GITHUB_ENV

    - name: Rebuild R environments
      if: env.files != ''
      run: |
        for file in ${{ env.files }}; do
          dir=$(dirname "$file")
          echo "Building renv for $dir"
          Rscript -e "renv::restore(lockfile = '$dir/renv.lock')"
        done
